name: Example Test
enabled: true
trigger:
    type: app_launch
    target: explorer.exe
actions:
    - type: set_memory_cap
      value: 70
    - type: temporary_exemption
      value: 0
stop_condition:
    type: app_close
    target: explorer.exe
