import React, { useState, useEffect } from 'react';
import './Dashboard.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSlidersH } from '@fortawesome/free-solid-svg-icons';

// wails Autogenerated bindings
import { GetLiveStats, SetMemoryCap } from '../../wailsjs/go/main/App'; 

export function Dashboard({ config, onUpdateConfig }) {
  // use config values or defaults
  const ramHeadroom = config ? (100 - config.enforcement.memory_cap) : 20;
  const cpuCeiling = config ? config.enforcement.cpu_ceiling : 70;

  const [stats, setStats] = useState({
    cpuUsage: 0, ramUsage: 0, totalRam: 0, processCount: 0
  });

  useEffect(() => {
    const updateStats = async () => {
      try {
        const data = await GetLiveStats();
        setStats(data);
      } catch (err) {
        console.error("Cura Engine Link Error:", err);
      }
    };
    updateStats();
    const interval = setInterval(updateStats, 2000);
    return () => clearInterval(interval);
  }, []);

  const handleRamChange = (e) => {
    const headroom = parseInt(e.target.value);
    const newCap = parseFloat(100 - headroom);
    
    // tell Go memory manager
    SetMemoryCap(newCap);
    
    // persist to TOML via App.jsx handler
    onUpdateConfig('memory_cap', newCap);
  };

  const handleCpuChange = (e) => {
    const val = parseInt(e.target.value);
    onUpdateConfig('cpu_ceiling', parseFloat(val));
  };

  const isRamExceeded = stats.ramUsage > (100 - ramHeadroom);

  return (
    <div className="dashboard-container">
      {/* Real-time Status Section */}
      <section className="guarantee-grid">
        
        {/* Memory Ring: Shows Actual Usage vs User Cap */}
        <div className="guarantee-card">
          <div className="ring-container">
            <svg className="ring-svg">
              <circle className="ring-bg" cx="56" cy="56" r="48" />
              <circle 
                className="ring-progress ram" 
                cx="56" cy="56" r="48" 
                style={{ 
                    strokeDashoffset: 301.59 - (301.59 * stats.ramUsage) / 100,
                    stroke: isRamExceeded ? '#ef4444' : 'var(--emerald)' 
                }}
              />
            </svg>
            <div className="ring-label">
              <span className="percent">{Math.round(stats.ramUsage)}%</span>
              <span className="label">USED</span>
            </div>
          </div>
          <div className="card-info">
            <h3>System RAM</h3>
            <p>{stats.totalRam}GB Total Architecture</p>
            <div className={`status-badge ${isRamExceeded ? 'warning' : 'optimal'}`}>
              {isRamExceeded ? 'ENFORCING CAP' : 'OPTIMAL'}
            </div>
          </div>
        </div>

        {/* CPU Ring: Shows Current System Load */}
        <div className="guarantee-card">
          <div className="ring-container">
            <svg className="ring-svg">
              <circle className="ring-bg" cx="56" cy="56" r="48" />
              <circle 
                className="ring-progress cpu" 
                cx="56" cy="56" r="48" 
                style={{ strokeDashoffset: 301.59 - (301.59 * stats.cpuUsage) / 100 }}
              />
            </svg>
            <div className="ring-label">
              <span className="percent">{Math.round(stats.cpuUsage)}%</span>
              <span className="label">LOAD</span>
            </div>
          </div>
          <div className="card-info">
            <h3>CPU Activity</h3>
            <p>Ceiling set to {cpuCeiling}%</p>
            <div className="status-badge optimal">MONITORING</div>
          </div>
        </div>
      </section>

      {/* Control Section: The Cap */}
      <section className="controls-section">
        <h3 className="section-title">
          <FontAwesomeIcon icon={faSlidersH} className="title-icon" />
          The Cap
        </h3>
        
        <div className="slider-grid">
          <div className="control-box">
            <div className="box-header">
              <div className="text">
                <h4>Memory Reserve</h4>
                <p>Ensures {ramHeadroom}% stays free</p>
              </div>
              <div className="value-display">
                <span className="val">{ramHeadroom}</span><span className="unit">%</span>
              </div>
            </div>
            <input 
              type="range" 
              className="cura-slider" 
              min="5" max="90"
              value={ramHeadroom} 
              onChange={handleRamChange} 
            />
          </div>

          <div className="control-box">
            <div className="box-header">
              <div className="text">
                <h4>CPU Ceiling</h4>
                <p>Max global processing limit</p>
              </div>
              <div className="value-display">
                <span className="val">{cpuCeiling}</span><span className="unit">%</span>
              </div>
            </div>
            <input 
              type="range" 
              className="cura-slider cpu-accent" 
              min="10" max="100"
              value={cpuCeiling} 
              onChange={handleCpuChange} 
            />
          </div>
        </div>
      </section>
    </div>
  );
}